version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ensemble-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ensemble-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

